i2prouter: abort immediately if I2P_CONFIG_DIR cannot be created

diff --git a/installer/resources/i2prouter b/installer/resources/i2prouter
--- a/installer/resources/i2prouter
+++ b/installer/resources/i2prouter
@@ -877,13 +877,21 @@ waitforwrapperstop() {
     done
 }
 
+create_config_dir() {
+    if ! mkdir -p "$I2P_CONFIG_DIR"; then
+        echo "Error creating $I2P_CONFIG_DIR! Edit $0 and set I2P_CONFIG_DIR" >&2
+        echo "to the correct location." >&2
+        exit 1
+    fi
+}
+
 launchdinternal() {
     getpid
     trap launchdtrap TERM
     if [ "X$pid" = "X" ]
     then
         prepAdditionalParams "$@"
-        mkdir -p "$PIDDIR" "$LOGDIR"
+        create_config_dir
 
         # The string passed to eval must handles spaces in paths correctly.
         COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" wrapper.name=\"$APP_NAME\" wrapper.java.command=\"$JAVABINARY\" wrapper.displayname=\"$APP_LONG_NAME\" wrapper.daemonize=TRUE $ANCHORPROP $IGNOREPROP $STATUSPROP $COMMANDPROP $LOCKPROP $LOGPROP wrapper.script.version=3.5.17 $ADDITIONAL_PARA"
@@ -907,7 +915,7 @@ console() {
         trap '' 3 2
 
         prepAdditionalParams "$@"
-        mkdir -p "$PIDDIR" "$LOGDIR"
+        create_config_dir
 
         # The string passed to eval must handles spaces in paths correctly.
         COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.java.command=\"$JAVABINARY\" wrapper.pidfile=\"$PIDFILE\" wrapper.name=\"$APP_NAME\" wrapper.displayname=\"$APP_LONG_NAME\" $ANCHORPROP $STATUSPROP $COMMANDPROP $LOCKPROP $LOGPROP wrapper.script.version=3.5.17 $ADDITIONAL_PARA"
@@ -1033,7 +1041,7 @@ start() {
     if [ "X$pid" = "X" ]
     then
         prepAdditionalParams "$@"
-        mkdir -p "$PIDDIR" "$LOGDIR"
+        create_config_dir
 
         # The string passed to eval must handles spaces in paths correctly.
         COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.java.command=\"$JAVABINARY\" wrapper.pidfile=\"$PIDFILE\" wrapper.name=\"$APP_NAME\" wrapper.displayname=\"$APP_LONG_NAME\" wrapper.daemonize=TRUE $ANCHORPROP $IGNOREPROP $STATUSPROP $COMMANDPROP $LOCKPROP $LOGPROP wrapper.script.version=3.5.17 $ADDITIONAL_PARA"
