Wrapper: Update to wrapper 3.5.29 All binaries from Tanuki delta pack, except for armhf, compiled on Raspberry Pi:   ant 1.8.2   javac 1.6.0_38   gcc 4.6.3-14+rpi1 Windows binaries remain unchanged as we must recompile them ourselves (32 bit just to change the icon; 64 bit is not provided by Tanuki) Old 3.5.25 wrapper.jar moved to win-all, use it in windows-only installer so it will be consistent with the old binaries. Fixes wrapper failure on FreeBSD 10 (ticket #1118) Minor i2prouter script fixes for FreeBSD 10, from anonimal (ticket #1118)

diff --git a/installer/resources/i2prouter b/installer/resources/i2prouter
--- a/installer/resources/i2prouter
+++ b/installer/resources/i2prouter
@@ -206,13 +206,15 @@ unsupported() {
 
 freebsd10() {
     echo
-    echo "The current version of the Tanuki wrapper does not"
-    echo "support FreeBSD 10."
+    echo "The current version of the Tanuki wrapper that is bundled"
+    echo "with I2P does not support FreeBSD 10."
     echo
-    echo "See https://trac.i2p2.de/ticket/1118 for more information"
-    echo "and a workaround for this issue."
+    echo "See http://trac.i2p2.de/ticket/1118#comment:13 for a work-around."
+    echo "After applying the work-around, as a normal user or a dedicated"
+    echo "i2p user, you can then run:"
+    echo "$ ./i2prouter start"
     echo
-    echo "In the meantime, you may start I2P by running the script"
+    echo "Or, you may also start I2P by running the script:"
     echo "${I2P}/runplain.sh"
     echo
 }
@@ -227,11 +229,11 @@ failed() {
                     ;;
                 *)
                     # We should never get here on recent versions of FreeBSD
-                    if ! $(pkg_info -E 'libiconv*' > /dev/null 2>&1); then
+                    if ! $(pkg info -E 'libiconv*' > /dev/null 2>&1); then
                         echo
                         echo "The wrapper requires libiconv."
                         echo
-                        echo "It can be installed with pkg_add -r libiconv"
+                        echo "It can be installed with pkg install libiconv"
                         echo
                     fi
                     ;;
