Fix ticket #514 (debconf values are overwritten upon installation)

diff --git a/debian/i2p.init b/debian/i2p.init
--- a/debian/i2p.init
+++ b/debian/i2p.init
@@ -52,6 +52,11 @@ I2P_ARGS="/etc/i2p/wrapper.config \
 # read config file
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
+if [ -z "$RUN_DAEMON" ]; then
+	echo "/etc/default/$NAME is not set. Aborting."
+	exit 1
+fi
+
 case "$RUN_DAEMON" in
         [NnFf]*)
                 log_action_msg "$DESC daemon disabled in /etc/default/$NAME".
