Add wrapper.java.maxmemory to debconf
The amount of RAM that I2P is limited to can be adjusted using debconf. The
value in /etc/i2p/wrapper.config is stored in the debconf db and is written to
/etc/default/i2p.

diff --git a/debian/i2p.postinst b/debian/i2p.postinst
--- a/debian/i2p.postinst
+++ b/debian/i2p.postinst
@@ -12,75 +12,88 @@ db_version 2.0
 
 
 case "$1" in
-	configure|reconfigure)
-		if [ ! -e $conffile ]; then
-			echo "# Defaults for i2p initscript (/etc/init.d/i2p" >> $conffile
-			echo "# This is a posix shell fragment" >> $conffile
-			echo >> $conffile
-			echo "# [automatically edited by postinst, do not change line format ]" >> $conffile
-			echo "# Run 'dpkg-reconfigure -plow i2p' to change these values." >> $conffile
-			echo >> $conffile
-			echo "RUN_DAEMON=" >> $conffile
-			echo "I2PUSER=" >> $conffile
-		fi
+    configure|reconfigure)
+        if [ ! -e $conffile ]; then
+            echo "# Defaults for i2p initscript (/etc/init.d/i2p" >> $conffile
+            echo "# This is a posix shell fragment" >> $conffile
+            echo >> $conffile
+            echo "# [automatically edited by postinst, do not change line format ]" >> $conffile
+            echo "# Run 'dpkg-reconfigure -plow i2p' to change these values." >> $conffile
+            echo >> $conffile
+            echo "RUN_DAEMON=" >> $conffile
+            echo "I2PUSER=" >> $conffile
+            echo "# The next value is also wrapper.java.maxmemory in /etc/i2p/wrapper.config" >> $conffile
+            echo "MEMORYLIMIT=" >> $conffile
+        fi
 
-		db_get i2p/daemon
-		RUN_DAEMON="$RET"
-		db_get i2p/user
-		I2PUSER="$RET"
+        db_get i2p/daemon
+        RUN_DAEMON="$RET"
+        db_get i2p/user
+        I2PUSER="$RET"
+        db_get i2p/memory
+        MEMORYLIMIT="$RET"
 
-		cp -a -f $conffile $conffile.tmp
+        cp -a -f $conffile $conffile.tmp
 
-		# If the admin deleted or commented some variables but then set them via debconf,
-		# (re-)add them to the conffile.
-		test -z "$RUN_DAEMON" || grep -Eq '^ *RUN_DAEMON=' $conffile || \
-			echo "RUN_DAEMON=" >> $conffile
-		test -z "$I2PUSER" || grep -Eq '^ *I2PUSER=' $conffile || \
-			echo "I2PUSER=" >> $conffile
+        # If the admin deleted or commented some variables but then set them via debconf,
+        # (re-)add them to the conffile.
+        test -z "$RUN_DAEMON" || grep -Eq '^ *RUN_DAEMON=' $conffile || \
+            echo "RUN_DAEMON=" >> $conffile
+        test -z "$I2PUSER" || grep -Eq '^ *I2PUSER=' $conffile || \
+            echo "I2PUSER=" >> $conffile
+        test -z "$MEMORYLIMIT" || grep -Eq '^ *MEMORYLIMIT=' $conffile || \
+            echo "MEMORYLIMIT=" >> $conffile
 
-		if [ -z $RUN_DAEMON ]; then
-			RUN_DAEMON="false"
-			I2PUSER="i2psvc"
-		fi
+        if [ -z $RUN_DAEMON ]; then
+            RUN_DAEMON="false"
+            I2PUSER="i2psvc"
+        fi
 
-		sed -e "s/^ *RUN_DAEMON=.*/RUN_DAEMON=\"$RUN_DAEMON\"/" \
-			-e "s/^ *I2PUSER=.*/I2PUSER=\"$I2PUSER\"/" \
-			< $conffile > $conffile.tmp
-		mv -f $conffile.tmp $conffile
 
-	migrate_existing_user(){
-		# Adjust the user/group in /etc/passwd, mainly for upgrades from old packages that didn't
-		# create $I2PSYSUSER as a system group/user
-		usermod -c "I2P Router Daemon" -m -d $I2PHOME -g $I2PSYSUSER -s "/bin/false" \
-			-l $I2PSYSUSER -e 1 > /dev/null 2>&1
-		echo "Existing user migrated, home directory moved to $I2PHOME"
-	}
 
-	# Create user and group as a system user.
-	adduser --system --quiet --group --home $I2PHOME $I2PSYSUSER || migrate_existing_user
+        sed -e "s/^ *RUN_DAEMON=.*/RUN_DAEMON=\"$RUN_DAEMON\"/" \
+            -e "s/^ *I2PUSER=.*/I2PUSER=\"$I2PUSER\"/" \
+            -e "s/^ *MEMORYLIMIT=.*/MEMORYLIMIT=\"$MEMORYLIMIT\"/" \
+            < $conffile > $conffile.tmp
+        mv -f $conffile.tmp $conffile
 
-	[ -d /var/log/i2p ] || mkdir -m0750 /var/log/i2p
-	chown -f -R $I2PSYSUSER:adm /var/log/i2p
+        sed -e "s/^ *wrapper\.java\.maxmemory=.*/wrapper\.java\.maxmemory=$MEMORYLIMIT/" \
+            < /etc/i2p/wrapper.config > /etc/i2p/wrapper.config.tmp
+        mv -f /etc/i2p/wrapper.config.tmp /etc/i2p/wrapper.config
 
-	# Has someone set the permissions with dpkg-statoverride? If so, obey them.
-	if ! dpkg-statoverride --list $I2PHOME > /dev/null 2>&1
-	then
-		chown -f -R $I2PSYSUSER:$I2PSYSUSER $I2PHOME
-		chmod -f u=rwx,g=rxs,o= $I2PHOME
-	fi
+    migrate_existing_user(){
+        # Adjust the user/group in /etc/passwd, mainly for upgrades from old packages that didn't
+        # create $I2PSYSUSER as a system group/user
+        usermod -c "I2P Router Daemon" -m -d $I2PHOME -g $I2PSYSUSER -s "/bin/false" \
+            -l $I2PSYSUSER -e 1 > /dev/null 2>&1
+        echo "Existing user migrated, home directory moved to $I2PHOME"
+    }
 
-	db_stop
+    # Create user and group as a system user.
+    adduser --system --quiet --group --home $I2PHOME $I2PSYSUSER || migrate_existing_user
+
+    [ -d /var/log/i2p ] || mkdir -m0750 /var/log/i2p
+    chown -f -R $I2PSYSUSER:adm /var/log/i2p
+
+    # Has someone set the permissions with dpkg-statoverride? If so, obey them.
+    if ! dpkg-statoverride --list $I2PHOME > /dev/null 2>&1
+    then
+        chown -f -R $I2PSYSUSER:$I2PSYSUSER $I2PHOME
+        chmod -f u=rwx,g=rxs,o= $I2PHOME
+    fi
+
+    db_stop
 ;;
 abort-upgrade|abort-remove|abort-deconfigure)
-	echo "Aborting upgrade"
-	exit 0
-	;;
+    echo "Aborting upgrade"
+    exit 0
+    ;;
 *)
         echo "postinst called with unknown argument \`$1'" >&2
                 exit 0
                 ;;
 esac
-	
+    
 #DEBHELPER#
 
 exit 0
